# Generated by Django 4.2.30 on 2026-06-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gleba',
            fields=[
                ('id_gleby', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('typ', models.CharField(blank=True, max_length=100, null=True)),
                ('ph_gleby', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gleba',
            },
        ),
        migrations.CreateModel(
            name='Kolekcja',
            fields=[
                ('id_kolekcji', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kolekcji', models.CharField(max_length=100)),
                ('data_posadzenia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'kolekcja',
            },
        ),
        migrations.CreateModel(
            name='Rodzaj',
            fields=[
                ('id_rodzaju', models.AutoField(primary_key=True, serialize=False)),
                ('rodzaj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rodzaj',
            },
        ),
        migrations.CreateModel(
            name='WarunkiHodowli',
            fields=[
                ('id_warunku', models.AutoField(primary_key=True, serialize=False)),
                ('wilgotnosc', models.CharField(blank=True, max_length=50, null=True)),
                ('naslonecznienie', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_maks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'warunki_hodowli',
            },
        ),
        migrations.CreateModel(
            name='Roslina',
            fields=[
                ('id_rosliny', models.AutoField(primary_key=True, serialize=False)),
                ('gatunek', models.CharField(db_index=True, max_length=100)),
                ('nazwa_powszechna', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('okres_kwitnienia', models.CharField(blank=True, max_length=50, null=True)),
                ('id_kolekcji', models.ForeignKey(blank=True, db_column='id_kolekcji', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rosliny', to='app.kolekcja')),
                ('id_rodzaju', models.ForeignKey(blank=True, db_column='id_rodzaju', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rosliny', to='app.rodzaj')),
            ],
            options={
                'db_table': 'roslina',
            },
        ),
        migrations.AddField(
            model_name='rodzaj',
            name='id_warunku',
            field=models.ForeignKey(blank=True, db_column='id_warunku', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.warunkihodowli'),
        ),
        migrations.CreateModel(
            name='Relacja',
            fields=[
                ('id_relacji', models.AutoField(primary_key=True, serialize=False)),
                ('typ_relacji', models.CharField(choices=[('Allelopatia dodatnia', 'Allelopatia dodatnia'), ('Allelopatia ujemna', 'Allelopatia ujemna'), ('Konkurencja', 'Konkurencja'), ('Symbioza', 'Symbioza')], max_length=50)),
                ('id_rosliny_1', models.ForeignKey(db_column='id_rosliny_1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacje_start', to='app.roslina')),
                ('id_rosliny_2', models.ForeignKey(db_column='id_rosliny_2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacje_koniec', to='app.roslina')),
            ],
            options={
                'db_table': 'relacja',
            },
        ),
        migrations.CreateModel(
            name='Nawoz',
            fields=[
                ('id_nawozu', models.AutoField(primary_key=True, serialize=False)),
                ('producent', models.CharField(blank=True, max_length=100, null=True)),
                ('zawartosc_azotu', models.CharField(blank=True, max_length=50, null=True)),
                ('zawartosc_fosforu', models.CharField(blank=True, max_length=50, null=True)),
                ('id_gleby', models.ForeignKey(blank=True, db_column='id_gleby', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nawozy', to='app.gleba')),
            ],
            options={
                'db_table': 'nawoz',
            },
        ),
        migrations.AddField(
            model_name='kolekcja',
            name='id_warunku',
            field=models.ForeignKey(blank=True, db_column='id_warunku', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.warunkihodowli'),
        ),
        migrations.AddField(
            model_name='gleba',
            name='id_warunku',
            field=models.ForeignKey(blank=True, db_column='id_warunku', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gleby', to='app.warunkihodowli'),
        ),
    ]
