# Generated by Django 4.2.30 on 2026-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gleba',
            index=models.Index(fields=['typ'], name='idx_gleba_typ'),
        ),
        migrations.AddIndex(
            model_name='kolekcja',
            index=models.Index(fields=['status'], name='idx_kolekcja_status'),
        ),
        migrations.AddIndex(
            model_name='kolekcja',
            index=models.Index(fields=['data_posadzenia'], name='idx_kolekcja_data'),
        ),
        migrations.AddIndex(
            model_name='nawoz',
            index=models.Index(fields=['producent'], name='idx_nawoz_producent'),
        ),
        migrations.AddIndex(
            model_name='relacja',
            index=models.Index(fields=['typ_relacji'], name='idx_relacja_typ'),
        ),
        migrations.AddIndex(
            model_name='rodzaj',
            index=models.Index(fields=['rodzaj'], name='idx_rodzaj_nazwa'),
        ),
        migrations.AddIndex(
            model_name='roslina',
            index=models.Index(fields=['gatunek', 'nazwa_powszechna'], name='idx_roslina_gatunek_nazwa'),
        ),
        migrations.AddIndex(
            model_name='roslina',
            index=models.Index(fields=['okres_kwitnienia'], name='idx_roslina_kwitnienie'),
        ),
        migrations.AddIndex(
            model_name='roslina',
            index=models.Index(fields=['id_kolekcji'], name='idx_roslina_kolekcja'),
        ),
    ]
